### ISSUE TITLE
Design basic CI/CD pipeline

### ISSUE THREAD

**Issue by uwardlaw** [dev4vater/vater#140]
- [ ] Produce a draw.io diagram for how the pipeline will test / build
- [ ] Ensure the pipeline proposed will support tests of all critical software components (see #40 for some suggestions)
  - CLI Python testing
  - Semaphore GUI testing
  - Ansible task testing
  - etc
- [ ] Develop a few basic tests for critical software components in MVP
  - E.g. pylint
  - E.g. `terraform fmt` / `packer validate` 
- [ ] Design a build process based on `group_vars` in `rous` that will
  - [ ] Create a new control VM
  - [ ] Setup control (`control.py` / `launch.ps1`)
  - [ ] Build ISOs 
  - [ ] Build templates
  - [ ] Somehow package up the templates and control for manual migration to an air gapped vCenter

**Comment by rmfirth** [comment]
I think we are going to run into a problem here where the Jenkins UI is needed in order to configure jobs. A pipeline can be defined as code, but the job itself is created in the UI.

@uwardlaw What about defining the deployment of control, testing, and packaging as an ansible playbook instead? Have we considered that option?

**Comment by uwardlaw** [comment]
We have, and in general we try hard to do things with the best fitting tool. Ansible could also configure VMs and deploy infrastructure but Packer and Terraform do it better.

Have you explored the Jenkins API or CLI? Either can probably be manipulated with Python and follows the pattern we took with Semaphore and Terraform.

**Comment by uwardlaw** [comment]
Merge #24

**Comment by rmfirth** [comment]
Created a preliminary diagram for us to discuss (cannot commit it due to lack of proper permissions on this repository):
https://drive.google.com/file/d/1m-r5oRwiZPI16zjs1GRMzcCAAxMdM1XX/view?usp=sharing

@uwardlaw @rylagek @marissaeinhorn

**Comment by uwardlaw** [comment]
@rmfirth I have some initial comments / discussion points

- Test Control
  - The req is to have the pipeline be fully automated, so having a user go through and have to find the "new" Control VM and start the pipe line isn't a good idea
  - How about using a distributed Jenkins type deployment?
  - There's also the CLI / API. The "creating" Jenkins can reach into the "new" Jenkins and start the pipeline
  - Also, I'm not sure how Jenkins wants to execute tasks, but why not establish an SSH connection into the "new" Jenkins and run the tasks that way?

- Build ISOs / Build Templates
  - The relationship between `semaphore.py` setup functions (create API key, project, envionrment, etc) and the `buildISOs.yml` and `buildVMs.yml` is unclear to me

- End provision / package pipeline
  - How will we package `Control` and the templates? Can templates just be copied if they're in the right file? I feel like there's an export process

- Start test deploy pipeline
  - Maybe we should use the `dev.py` approach here and configure the the `Control` VM as development platform so that passwords / users come directly from the `config.json`, and then run a `vater clean` at the end of the pipeline. This will make testing easier / more automatic.
  - If vault is setup the one password given can also be used earlier in PROVISION & DEPLOY CONTROL and then given again at the start of the test

**Comment by rmfirth** [comment]
- Test Control
  1. Correct, the pipeline should be as automated as possible, but we are talking about running tests on a newly provisioned VM. I've been doing some research and either I'm not coming up with the right search terms or that's not a very normal thing to do. You could have the VM run its own Jenkins job and then _try_ (emphasis on the _try_) to have the first Jenkins job depend on the output of the second Jenkins job, but that is also a very abnormal thing to do and there's not really an elegant way to do it that I could find. We would be creating a maintenance nightmare by implementing the code that would be necessary to do it.
  2. Distributed jenkins deployment isn't a bad idea but not really a great option. Adding a new node happens through the Jenkins API and I don't think we are going to find a good way to add a new node _in the middle of a job_, much less have that node be a machine that was created during the job. 
  3. Yes
  4. I already looked into this - SSH with jenkins is possible but not for doing what we want. It is used for running scripts before/after a job on a remote host. That doesn't really help us because this needs to happen in the middle of a job. The next best thing would be a distributed Jenkins job, which has the obstacles I already mentioned

Part of the problem with this "Test Control" is, like I said, we are trying to verify the working state of a VM from outside it, which is unusual based on my research. Please correct me if you know otherwise. That is why one option MIGHT be to log onto the Jenkins UI of the new machine (all you need is the IP address) and manually trigger a _different_ pipeline that verifies the internal state of the machine. Is it ideal? No, but it's an option, depending on how often we anticipate deploying machines through this pipeline

- I will clarify on the diagram. The "create API key, project, etc." steps are necessary precursors for getting the buildISOs task to run. First, we need the "Parent" VM to create an API key so it can run tasks through the Semaphore API, then we need to create an environment specific to packaging (it will tell ansible where the templates should be placed on the datastore)

- End provision / package pipeline
  - how will we package `Control` and the templates? This is a good question - my understanding was that COTR would be copying a folder from the datastore and then copying that same folder onto another datastore in the air-gapped datacenter. I don't know a lot about how that process works, so I will look into what is necessary for "exporting"

- Start test deploy pipeline
  1. Specifically, which steps are you saying would be removed/automated by using `dev.py`
  2. Agreed

**Comment by rmfirth** [comment]
Update: after some discussion, I was wrong about this part:

> You could have the VM run its own Jenkins job and then try (emphasis on the try) to have the first Jenkins job depend on the output of the second Jenkins job, but that is also a very abnormal thing to do and there's not really an elegant way to do it 
There _is_ a good way to do this using the [Parameterized Remote Trigger plugin](https://github.com/jenkinsci/parameterized-remote-trigger-plugin/blob/master/README_PipelineConfiguration.md)

The only problem to resolve now is that the parent Jenkins job needs to get the IP address of the child "Control" VM - ideally this would be an output of the `control.py` script that provisions and launches the new VM.

**Comment by rmfirth** [comment]
Blocked by:  #100

**Comment by marissaeinhorn** [comment]
Not required for RANS implementation or interim solution.  Detailed request for an automated testing method for Foundry content development in #236
