### ISSUE TITLE
Utilize Vsphere clusters and distributed switches with terraform 

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#156]
When migrating to production will need to distribute/load balance VMs.

**Comment by Summerhays319** [comment]
Has anyone looked at the possibility of incorporating HashiCorp Consul (https://www.consul.io/docs) to do load balancing and network management functions as another alternative?

**Comment by uwardlaw** [comment]
To clarify, this issue came after a discussion with our Vsphere engineer
about networking following a short demo. He said we'd need to start using
distributed switches instead of regular vswitches.

We do love Hashicorp, but no. A very light skim of their their feature
introduction did not make Consul's place in VATER obvious to me. We don't
really need to actually (or didn't think we needed to) load balance
services. Did you want to make an argument that we should start?

**Comment by marissaeinhorn** [comment]
Ducknet is not equipped with the physical hardware to test using distributed switches.  Will need to work with the contractors and test on Labnet

**Comment by marissaeinhorn** [comment]
Just need to reference existing virtual switch, not make a new one.  [ref](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/distributed_virtual_switch)

Must include optional argument `number_of_ports =8 ` to have ports auto assigned to port group.  Should automatically add additional ports if needed.

**Comment by marissaeinhorn** [comment]
```
data "vsphere_distributed_virtual_switch" "vds" {
  name = var.vsphere_distributed_switch
  datacenter_id = <typical>
}
resource "vsphere_distributed_port_group" "test" {
  name = <name>
  distributed_virtual_switch_uuid = "${data.vsphere_distributed_virtual_switch.vds.id}"
  avctive_uplinks = ["${data.vsphere_distributed_virtual_switch.vds.uplins[0]},
                                ${data.vsphere_distributed_virtual_switch.vds.uplins[1]}
                            ]
 number_of_ports = 8

}
```

then reference network normally and assign to VM
