### ISSUE TITLE
Research whether GNS3 meets ICF needs

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#197]
GNS3 vs packet tracer.  Goddard is concerned about automatic grading mechanisms.

**Comment by ChrisZ735** [comment]
[researchgns3notes.txt](https://github.com/dev4vater/vater/files/8256604/researchgns3notes.txt)

**Comment by ChrisZ735** [comment]
Supported OS:    
    Windows 7 (64 bit)
    Windows 8 (64 bit)
    Windows 10 (64 bit)
    Windows Server 2012 (64 bit)
    Windows Server 2016 (64 bit)
    Mac OS X Mavericks (version 10.9) and later.
    Linux

Additional platforms that can run the GNS3 VM:

    ESXi
    Bare Metal Cloud based providers such as Packet.net

**Comment by ChrisZ735** [comment]
https://www.gns3.com/community/featured/gns3-lab-automation
This seems useful

**Comment by marissaeinhorn** [comment]
Automated setup of GNS environment - need to dig deeper to see if this can be modified to fit our needs.  [github](https://github.com/adosztal/gns3-automation)

**Comment by tricksterqueen** [comment]
These notes are how to install GNS3 using VirtualBox on a Windows device using the GNS3 VM. This does not include adding routers or layer 3 switches to GNS3. 
[GNS3 Install with Windows and VirtualBox.txt](https://github.com/dev4vater/vater/files/8374787/GNS3.Install.with.Windows.and.VirtualBox.txt) 
This was attempted both on a bare metal computer (which worked)
and on an instance of the temporary Windows Development Environment in VirtualBox (this did not work). Since GNS3 uses a VM as a server and nesting Virtual Machines can cause issues, this would likely need additional work before it is used on a range. Conversely, this might be possible by working without the GSN3 VM.

**Comment by tricksterqueen** [comment]
These notes are how to install GNS3 using VMware Workstation on a Windows device using the GNS3 VM. This does not include adding routers or layer 3 switches to GNS3.
[GNS3 Install with Windows and VMWare.txt](https://github.com/dev4vater/vater/files/8382259/GNS3.Install.with.Windows.and.VMWare.txt)
GSN3 lists VMware as the preferred VM server and it does seem to have less wait time when changing settings compared to VirtualBox, but this has not been timed and compared on the computers that will be used for ICF

**Comment by tricksterqueen** [comment]
These notes are on how to install GNS3 on a Windows device without using the GNS3 VM. This does not include adding routers or layer 3 switches to GNS3.
[GNS3 Install with Windows and no GNS3 VM.txt](https://github.com/dev4vater/vater/files/8383343/GNS3.Install.with.Windows.and.no.GNS3.VM.txt)
There are fewer files required to get this running than anything using the GNS3 VM and seems to be the simplest installation.
Since it doesn't use the GNS3 VM, it would be the easiest to have running inside a virtual machine.
It reportedly can't use as many appliances as when using GNS3 VM, but I am unsure what those additional appliances would be.

**Comment by tricksterqueen** [comment]
These instructions explain how to add routers and layer 3/multi-layer switches.
[Routers and Mult-Layer Switches.txt](https://github.com/dev4vater/vater/files/8383587/Routers.and.Mult-Layer.Switches.txt)

**Comment by marissaeinhorn** [comment]
Closing research issue.  ICF is evaluating GNS3 labs built by 338th for use in the course in addition to existing RANS & Immersive Labs content.  Don Summerhays is new POC.  Reopen if GNS3 labs plan to integrate with VATER
