### ISSUE TITLE
IADS setup/notes

### ISSUE THREAD

**Issue by Timo604** [dev4vater/vater#260]
config script couldn't find the nginx package that the config script needs to install. This should be from the VM running out of disk space. The new VM has enough. 

The README with installation instructions is in fs-installation.tar.gz. Extract it and follow those directions to place the files in the right locations, edit some config files as needed, etc. All files are provisioned by Packer to /home/ubuntu

Along with adding the extra disk space, Packer now provisions the vm as dual nic'd and will keep the spearnet ip on its first interface as for management and configure the second interface as the exercise interface

**Comment by Grunt12** [comment]
Things to do before running script:
scp .tar.gz's over to IADS Controller into ~/
scp script over to IADS Controller into ~/
sudo apt-get install dos2unix
mv IADS-Setup.sh.txt IADS-Setup.sh
sudo chmod u+x IADS-Setup.sh
update paths in setup script
update interfaces in sed commands for management and exercise 
place setup in home directory

Snapshot located  R2R_4 in Control-setupTesting

**Comment by Grunt12** [comment]
**Do before running configure-host.sh:**
set static ip for exercise interface
change user directory in app.config.template

**Comment by Grunt12** [comment]
Team1 Controller is now working. Reset VM a few times and restarted nginx and exerciseControl.service. Page originally gave a bad gateway  and solved with saving the netplan config again and then applying  with the sudo netplan apply.

**Comment by marissaeinhorn** [comment]
@Donovan-Medina Can you take a look a the docker scripts that the STARTEX button triggers?  If we can identify what lines of code have dependencies on AFRLs gitlab server it'll help solve them after ACE is over.

**Comment by Donovan-Medina** [comment]
## Notes from today's test:
### Getting started running the exercise:
- ensure the services nginx and exerciseControl are running `service status <service-name>`
- exerciseControl essentially runs `scenarioControl -config <path to config>` allowing it to run on port 8000 and not conflict with nginx

### Maps not loading correctly:
- the container locations.pantheon.mgmt is trying to connect to a minio.mgmt that doesn't exist to load map assets instead of the db.mgmt container (running postgres)
- There is also the a warning that pops up periodically that something is trying to query from db.mgmt but cannot find it or cannot authenticate correctly to the postgres database.

As of now we have not found any dependencies missing. The images are bundled from AFRL. Will need to test cloning a "team-2" control and see if it attempts to pull from a private/unavailable repo to confirm.
